// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBUuygJPWx6NwL82PTbEisS8uaAdTp2vpk',
    appId: '1:1018415533699:web:63a5de77cdb80bea6d95b6',
    messagingSenderId: '1018415533699',
    projectId: 'test-f9fab',
    authDomain: 'test-f9fab.firebaseapp.com',
    storageBucket: 'test-f9fab.appspot.com',
    measurementId: 'G-QJVL5T7NG2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDPLAnAxx9tvHDBTrNtMJ1K43fa6NIbeaE',
    appId: '1:1018415533699:android:23714a49cb608ef56d95b6',
    messagingSenderId: '1018415533699',
    projectId: 'test-f9fab',
    storageBucket: 'test-f9fab.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZVe8xK4A7CtAZlz8BJEUJPGyn3PJ33dc',
    appId: '1:1018415533699:ios:2d80bbdb8c39df796d95b6',
    messagingSenderId: '1018415533699',
    projectId: 'test-f9fab',
    storageBucket: 'test-f9fab.appspot.com',
    iosClientId: '1018415533699-2js7jfcts980pmac0c522mbtki6spfki.apps.googleusercontent.com',
    iosBundleId: 'com.example.app',
  );
}
