// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCa5ewaE07himLDxUrU7sEywmAZRA9WJtg',
    appId: '1:943129182937:web:1f3349a4b9f6095e7cf4c8',
    messagingSenderId: '943129182937',
    projectId: 'facerecog-4d636',
    authDomain: 'facerecog-4d636.firebaseapp.com',
    storageBucket: 'facerecog-4d636.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC6AFK7X_d98-n7RGLoLz8NP3mdPojBoSU',
    appId: '1:943129182937:android:a2e14f0782a01ba97cf4c8',
    messagingSenderId: '943129182937',
    projectId: 'facerecog-4d636',
    storageBucket: 'facerecog-4d636.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBybh3Alhbgx6Y5OL_39qakXozPgLhr794',
    appId: '1:943129182937:ios:9b1192976c4b9f5e7cf4c8',
    messagingSenderId: '943129182937',
    projectId: 'facerecog-4d636',
    storageBucket: 'facerecog-4d636.appspot.com',
    iosClientId: '943129182937-vnigglu63p367gtbc8kp8ir7qqr3p9mq.apps.googleusercontent.com',
    iosBundleId: 'com.aldyn.facerecog',
  );
}
